# =====================================
# 💾 WORKFLOW.yaml
# =====================================
#
# プロジェクト: sum-it
# セッション間で情報を保持するためのセーブデータ。
#
# =====================================

workflow:
  version: "1.3"
  last_updated: "2026-02-02T05:20:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - 出力形式・議長のCRUDおよび連動機能の完成 ✅🛡️
    - 会議室本体のCRUD（タイトル・ホワイトボード・名簿・議長の一括更新保存、会議削除）の実装完了 ✅🏢✨
    - 会議テンプレート機能の完全実装 🆕🚀
        - `meeting_templates` コレクションの定義とFirestore CRUD関数の追加
        - 会議作成画面でのテンプレート選択・適用ロジックの実装
        - 会議作成と同時に現在の構成をテンプレートとして保存する機能の追加
    - 会議室作成UIの再構築（議長とエージェントをセットとして配置、テンプレート導線の強化）🎨💎

    【次のステップ】
    - AI会議実行ロジック（エージェントの発言ターン・LLM連携エンジン）の実装 🆕🔥
    - 議長ごとの進行・結論生成プロンプトの注入ロジック
    - 会議履歴の詳細閲覧と検索のブラッシュアップ

  progress:
    current_phase:
      number: 4
      name: "履歴管理 & テンプレート"
      status: "completed"
    
    current_task:
      description: "AI会議実行エンジンのコア実装"
      started_at: "2026-02-02T05:20:00+09:00"

  decisions:
    adopted:
      - id: "D011"
        date: "2026-02-02"
        decision: "会議構成テンプレート (MeetingTemplate) の導入"
        reason: "議長とエージェントの最強セットを再利用可能にし、会議の立ち上げを爆速化するため"
      - id: "D012"
        date: "2026-02-02"
        decision: "作成フロー内でのテンプレート同時保存"
        reason: "試行錯誤して決めたメンバー構成を、その場で資産化できるようにするため"

  features:
    completed:
      - id: "F-301"
        name: "会議テンプレート機能"
        status: "done"
        completed_at: "2026-02-02T05:18:00+09:00"
