# =====================================
# 💾 WORKFLOW.yaml
# =====================================
#
# プロジェクト: sum-it
# セッション間で情報を保持するためのセーブデータ。
#
# =====================================

workflow:
  version: "1.4"
  last_updated: "2026-02-02T11:55:00+09:00"

  last_session_summary: |
    【今回のセッションでやったこと】
    - 会議実行エンジン (Meeting Execution Engine) のコアロジック実装 ✅🔥
        - `workflow-engine.ts` に単独発言・並列発言・サマリー・一時停止の全ハンドラを実装。
    - 会議進行API (next / resume) の実装完了 ✅🔧
        - ユーザー介入後のホワイトボード更新を反映した再開フローを確立。
    - UIとエンジンの完全統合 🎨💎
        - ワークフロー選択からの会議作成、および会議室内での進行制御ボタンの実装。
    - ワークフロー基盤（型定義・Firestore CRUD）の整備完了。

    【次のステップ】
    - 実環境でのブラウザ疎通確認とバグFIX 🧪
    - 会議進行中のUX向上（タイピング演出、状態インジケーターなど）✨
    - 会議履歴のアーカイブ表示と検索機能の強化 📖

  progress:
    current_phase:
      number: 5
      name: "会議実行エンジン実装"
      status: "completed"
    
    current_task:
      description: "ブラウザでの動作確認とUXブラッシュアップ"
      started_at: "2026-02-02T11:55:00+09:00"

  decisions:
    adopted:
      - id: "D013"
        date: "2026-02-02"
        decision: "ステータス遷移への 'waiting' 導入"
        reason: "ユーザーがホワイトボードを修正したり口を挟んだりするタイミングを、AIの実行フローと安全に同期するため"
      - id: "D014"
        date: "2026-02-02"
        decision: "サマリー生成における GPT-4o 固定"
        reason: "会議の結論は最も賢いモデルに委ねることで、議論の質を保証するため"

  features:
    completed:
      - id: "F-401"
        name: "会議実行エンジン基盤"
        status: "done"
        completed_at: "2026-02-02T11:50:00+09:00"
      - id: "F-402"
        name: "ワークフロー進行・再開API"
        status: "done"
        completed_at: "2026-02-02T11:50:00+09:00"
